#ifndef ERR_MSG_H
# define ERR_MSG_H

#  define ALLOC_ERR "MEMORY ALLOCATION FAIL"

#  define NO_ARG_ERR "NO ARGUMENT WAS GIVEN"
#  define NOT_ENOUGH_ARG_ERR "NOT ENOUGH ARGUMENT WERE GIVEN"
#  define READ_ERR "read() FAIL"
#  define READ_FILE_ERR "JSON NOT FOUND"
#  define INVALID_JSON_ERR "INVALID JSON"

#  define JSON_INVALID_NAME_ERR "JSON | INVALID NAME OR NO NAME"
#  define JSON_INVALID_ALPHABET_ERR "JSON | INVALID ALPHABET OR NO ALPHABET"
#  define JSON_INVALID_CHARACTER_ALPHABET_ERR "JSON | INVALID ALPHABET CHARACTER"
#  define JSON_DUP_CHARACTER_ALPHABET_ERR "JSON | DUPLICATE CHARACTER IN ALPHABET"
#  define JSON_INVALID_BLANK_ERR "JSON | INVALID BLANK OR NO BLANK"
#  define JSON_BLANK_NOT_IN_ALPHABET_ERR "JSON | BLANK NOT IN ALPHABET"
#  define JSON_INVALID_STATE_LIST_ERR "JSON | INVALID STATE LIST OR NO STATE LIST"
#  define JSON_INVALID_STATE_ERR "JSON | INVALID STATE"
#  define JSON_DUP_STATE_ERR "JSON | DUPLICATE STATE IN STATE LIST"
#  define JSON_INVALID_INITIAL_ERR "JSON | INVALID INITIAL OR NO INITIAL"
#  define JSON_INITIAL_NOT_IN_STATE_LIST_ERR "JSON | INITIAL NOT IN STATE LIST"
#  define JSON_INVALID_FINAL_LIST_ERR "JSON | INVALID FINAL LIST OR NO FINAL LIST"
#  define JSON_INVALID_FINAL_ERR "JSON | INVALID FINAL"
#  define JSON_FINAL_NOT_IN_STATE_LIST_ERR "JSON | FINAL NOT IN STATE LIST"
#  define JSON_DUP_FINAL_ERR "JSON | DUPLICATE FINAL IN FINAL LIST"
#  define JSON_INVALID_TRANS_LIST_ERR "JSON | INVALID TRANSITION LIST OR NO TRANSITION LIST"
#  define JSON_INVALID_STATE_TRANS_ERR "JSON | INVALID STATE TRANSITION OR NO STATE TRANSITION"
#  define JSON_INVALID_TRANS_READ_ERR "JSON | INVALID READ OR NO READ IN TRANSITION"
#  define JSON_INVALID_TRANS_TO_STATE_ERR "JSON | INVALID TO_STATE OR NO TO_STATE IN TRANSITION"
#  define JSON_TRANS_TO_STATE_NOT_IN_STATE_LIST_ERR "JSON | TRANSITION TO_STATE NOT IN STATE LIST"
#  define JSON_INVALID_TRANS_WRITE_ERR "JSON | INVALID WRITE OR NO WRITE IN TRANSITION"
#  define JSON_INVALID_ACTION_ERR "JSON | INVALID ACTION OR NO ACTION IN TRANSITION"
#  define JSON_UNKNOWN_ACTION_ERR "JSON | TRANSITION ACTION NOT \"LEFT\" OR \"RIGHT\""

#endif
